//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpareParts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int PartId { get; set; }
        public string ResolutionPartName { get; set; }
        public string TagName { get; set; }
        public string PartNo { get; set; }
        public string PartName { get; set; }
        public string PartNoOrignal { get; set; }
        public int BrandId { get; set; }
        public int MachineId { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
